Allow newer python3 versions like 3.8 as well
 * Use the recommended process_message() signature for smtpd.DebuggingServer
   to avoid errors like <class 'TypeError'>:process_message() got an unexpected keyword argument 'mail_options' [/usr/lib/python3.8/asyncore.py|read|83] [/usr/lib/python3.8/asyncore.py|handle_read_event|420] [/usr/lib/python3.8/asynchat.py|handle_read|171] [/usr/lib/python3.8/smtpd.py|found_terminator|386]

 * Be dynamic about what type is the data argument when
   process_message() is called as with python 3.5 it is `str` where
   with python 3.8 ist is `bytes` without other changes.